site_name: Broz's Cookbook
site_url: https://CBroz1.github.io/cookbook/
site_description: Collection of adapted recipes
site_author: CBroz1

repo_url: https://github.com/CBroz1/cookbook
docs_dir: ./src/
edit_uri: blob/main/docs/src/

theme:
    name: material
    palette:
      - media: "(prefers-color-scheme: light)"
        scheme: my-default
        toggle:
          icon: material/brightness-7
          name: Switch to dark mode
      - media: "(prefers-color-scheme: dark)"
        scheme: slate
        toggle:
          icon: material/brightness-4
          name: Switch to light mode
    custom_dir: overrides
    logo: stylesheets/cook_icon.png
    favicon: stylesheets/cook_icon.png
    disable_nav_previous_next: true
    disable_nav_search: false
    navigation_depth: 2
    locale: en
    shortcuts:
        help:      72 # h # doesn't seem to be working
        next:      78 # n
        previous:  80 # p
        search:    83 # s
    features:
      - toc.integrate
      - navigation.sections
      - navigation.expand
      - navigation.top
      - navigation.instant   # saves loading time - 1 browser page
      - navigation.tracking  # even with above, changes URL by section
      # - navigation.tabs      # moves top level heading to tabs
      - search.suggest
      - search.share

nav:
  - Home:                   index.md
  - Entrees:
    - Black Bean Burgers:  1_Entrees/BlackBeanBurgers.md
    - Broccoli Casserole:  1_Entrees/BroccoliQuinoaCassarole.md
    - Brussels:  1_Entrees/Brussels.md
    - Coconut Curry Chicken:  1_Entrees/CoconutCurry.md
    - Coconut Kale Fried Rice:  1_Entrees/CoconutKaleRice.md
    - Crunchwraps:  1_Entrees/Crunchwraps.md
    - Felafel:  1_Entrees/Falafel.md
    - Latkas: 1_Entrees/Latkas.md
    - Spicy Udon:  1_Entrees/Udon.md
    - Summer Squash Pasta:  1_Entrees/SummerSquashPasta.md
    - Summer Squash Pasta: ./1_Entrees/SummerSquashPasta.md
    - Thai Quinoa Salad:  1_Entrees/ThaiQuinoaSalad.md
    - Vegetarian Chili:  1_Entrees/VegetarianChili.md
    - Vegetarian Enchiladas:  1_Entrees/VegetarianEnchiladas.md
  - Sides:
    - Bitchin Sauce:  2_Sides/BitchinDip.md
    - Cornbread:  2_Sides/Cornbread.md
    - Baba Ganoush: 2_Sides/BabaGanoush.md
  - Deserts:
    - Blueberry Muffins:  3_Desserts/BlueberryMuffins.md
    - Nutella brownies:  3_Desserts/NutellaBrownies.md
    - S’mores bars:  3_Desserts/SmoresBars.md

extra_css:
  - stylesheets/extra.css

plugins:
  - search
  - exclude:
      glob:
        - "temp*"
  - literate-nav:
      nav_file: navigation.md'
  - exclude-search:
      exclude:
        - "*/navigation.md"

markdown_extensions:
  - attr_list
  - tables
  - toc:
      permalink: true

extra:
  generator: false # Disable watermark
